spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_wines?verifyServerCertificate=false&useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: spring
    password: aqwserft234252
  jpa:
    hibernate:
      ddl-auto: update